name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches:
      - main  # Dispara o deploy sempre que houver push na main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm ci

      # 4. Gerar o build do projeto
      - name: Build do projeto
        run: npm run build

      # 5. Deploy para GitHub Pages
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true