name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main  # sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configura o Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # 3. Instala as dependências
      - name: Instalar dependências
        run: npm install

      # 4. Build do projeto
      - name: Build do projeto
        run: npm run build

      # 5. Publica na branch gh-pages
      - name: Deploy para GitHub Pages
        run: |
          git config --global user.name "HeitorPaula"
          git config --global user.email "heitor@example.com"
          npx gh-pages -d dist
